name: Build service Docker image

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets:
      SENTRY_DSN:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name:
        run: |
          echo "@schneefux:registry=https://npm.pkg.github.com" >> ./${{ inputs.service }}/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ./${{ inputs.service }}/.npmrc
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/schneefux/brawltime-${{ inputs.service }}
          flavor: |
            latest=true
          tags: |
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # GitHub Container Registry
      # https://github.com/docker/login-action#github-container-registry
      -
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.service }}/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GIT_REV=${{ github.sha }}
            BRANCH=${{ github.ref }}
            SENTRY_ORG=schneefux
            SENTRY_PROJECT=brawltime-ninja
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=gha,scope=${{ inputs.service }}
          cache-to: type=gha,scope=${{ inputs.service }},mode=max
